services:
  # PostgreSQL Database (Starts first)
  strapi-db:
    container_name: strapi-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:16.0-alpine
    env_file:
      - .env
      - .env.docker
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - educado-network

  # MongoDB Database (for backend)
  backend-db:
    container_name: backend-db
    restart: unless-stopped
    image: mongo:7.0
    env_file:
      - .env
      - .env.docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - backend-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - educado-network

  # Strapi CMS
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: ./strapi/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
      - .env.docker
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1337
      # Database Configuration (using standard Strapi names)
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapi-db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: false
      # Strapi Secrets
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - strapi-uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - educado-network
    depends_on:
      - strapi-db

  # Node.js Backend API
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
      - .env.docker
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${BACKEND_PORT}
      STRAPI_URL: ${STRAPI_URL}
      STRAPI_API_TOKEN: ${STRAPI_API_TOKEN}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      - educado-network
    depends_on:
      - strapi
      - backend-db

  # React Frontend with Nginx (Starts last)
  # STACK ENTRYPOINT. Proxies to backend and serves frontend.
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
      - .env.docker
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_STRAPI_URL: ${VITE_STRAPI_URL}
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - educado-network
    depends_on:
      - backend

volumes:
  strapi-data:
  strapi-uploads:
  backend-data:

networks:
  educado-network:
    name: ${NETWORK_NAME}
    driver: bridge
